Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'node_modules/**'
    - 'public/**'
    - 'tmp/**'
    - 'vendor/**'
    - 'log/**'
    - '*.json'
    - 'yarn.lock'