default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: vibes_api_development
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

test:
  <<: *default
  database: vibes_api_test
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # database: your_app_name_production
  # username: <%= ENV["POSTGRES_USER"] %>
  # password: <%= ENV["POSTGRES_PASSWORD"] %>