name: Ruby

on:
  push:
    branches:
      - main
      - develop
      - feature/add-meditation-app
  pull_request:
    branches:
      - main
      - develop
      - feature/add-meditation-app
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: bundle exec rubocop -d

    - name: Run tests
      run: bundle exec rake test